project:
  title: "egait-nn-segmentation"

title: "Gait Segmentation Model for Rotation Time Series Collected by a Wearable Sensor using Machine Learning"
author:
  - name: Manon Simonot
    corresponding: true
    email: manon.simonot@univ-nantes.fr
    affiliations:
      - name: Department of Mathematics Jean Leray, UMR CNRS 6629, Nantes University
  - name: Lise Bellanger
    email: lise.bellanger@univ-ubs.fr
    affiliations:
      - name: Lab-STICC Laboratory, UMR CNRS 6285, South Brittany University
  - name: Aymeric Stamm
    email: aymeric.stamm@cnrs.fr
    affiliations:
      - name: Department of Mathematics Jean Leray, UMR CNRS 6629, Nantes University
date: last-modified
date-modified: last-modified
abstract: >+
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere vestibulum facilisis. Aenean pretium orci augue, quis lobortis libero accumsan eu. Nam mollis lorem sit amet pelSlowsque ullamcorper. Curabitur lobortis libero eget malesuada vestibulum. Nam nec nibh massa. PelSlowsque porttitor cursus tellus. Mauris urna erat, rhoncus sed faucibus sit amet, venenatis eu ipsum.
keywords: [key1, key2, key3]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "xxxx"
  url: https://computo.sfds.asso.fr/template-computo-quarto
  publisher: "Société Française de Statistique"
  issn: "2824-7795"
bibliography: references.bib
github-user: computorg
repo: "template-computo-r"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
format:
  computo-html: default
  computo-pdf:
    cite-method: biblatex
    biblatexoptions: "sorting=none"
    header-includes:
      - \usepackage{longtable}
      - \usepackage{hhline}
      - \usepackage{enumitem}
tbl-cap-location: bottom
